name: cashier_app
description: "Cashier App with POS APP."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  file_picker: ^10.2.0
  path: ^1.8.2
  flutter_svg: ^2.0.9
  fl_chart: ^1.0.0
  data_table_2: ^2.0.3
  liquid_pull_to_refresh: ^3.0.1
  dio:
  get:
  intl: ^0.18.1
  video_player: ^2.8.1
  internet_connection_checker: ^1.0.0+1
  lottie: ^3.0.0
  mobile_scanner: 4.0.1
  shared_preferences:
  flutter_spinkit: ^5.2.0
  flutter_animated_dialog:
  device_info_plus:
  window_manager:
  http:
  flutter_gutter: ^2.2.0
  font_awesome_flutter:
  animated_snack_bar:
  flutter_cupertino_datetime_picker:
  dropdown_button2: ^2.1.3
  flutter_barcode_listener: ^0.1.3
  flutter_colorpicker:
  pin_keyboard: ^1.1.2
  qr_flutter: ^4.1.0
  settings_ui: ^2.0.2
  barcode_scan2:
  animated_splash_screen: ^1.3.0
  flutter_pos_printer_platform:
  collection:
  package_info_plus: ^8.3.0
  esc_pos_utils:
  printing:
  pdf:
  get_cli:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.2.0+1
  build_runner: ^2.4.5
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - lottie/
    - assets/
    - assets/images/
    - assets/background/
    - assets/background/restaurant.jpg
    - assets/images/noImage.jpg
  fonts:
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai-Regular.ttf
        - asset: assets/fonts/Dubai-Light.ttf
          weight: 300
        - asset: assets/fonts/Dubai-Medium.ttf
          weight: 500
        - asset: assets/fonts/Dubai-Bold.ttf
          weight: 700